evm-networks.json
tokens.json

Added the Binance Smart Chain (BEP-20) network.

Added Binance Smart Chain Network

---

chaindata.json

as requested by subsocial team

fix: remove unstable subsocial node

---

chaindata.json
schemas/json/chaindata.json

to help testing PR on subsquid that adds this property

feat: hydradx isUnknownFeeToken

---

chaindata.json

following ticket https://discord.com/channels/858891448271634473/1118963644143779840
on bifrost polkadot (might need to do the same on kusama) :
- added ASTR
- fixed VDOT and VSDOT

fix: bifrost polkadot balances

---

scripts/import-pjs-config.js

In this PR:
- 1Rpc have improved their offering recently, so unlisted them from our 'bad providers'
- Improved naming of RPC provider sort/filter categories to be more polite

Remove 1rpc from list of bad rpc providers

---

chaindata.json

as discussed. 
Decentralized IBP Monitoring: https://monitor.dotters.network/
Website: https://ibp.network/

add and update ibp nodes

---

chaindata.json

Added new supported networks and removed several deprecated endpoints

Updated OnFinality Endpoints

---

.gitignore
chaindata.json
evm-networks.json
testnets-chaindata.json

also includes a change to .gitignore to make it easy to switch from main to v3 branch

chore: update onfinality rpcs (v3 branch)

---

testnets-chaindata.json

Company website: [metaquity.xyz](https://www.metaquity.xyz/)
Point of contact: [here](https://discord.com/channels/858891448271634473/860710589235462144/1169761747993899099)

Add Metaquity network to testnets-chaindata.json

---

chaindata.json

https://twitter.com/XEnergyWeb/status/1745153658302447860?t=m8xA1O9FYPnjpSA8lukbDw

Add rpc for energy web x

---

data/chaindata.json

Temporary measure until we can get RPC fallback mechanism working in the portal.

chore: add Parity's RPCs

---

data/chaindata.json

We would like to add RadiumBlock rpc endpoints for Khala, Phala, Moonriver and Shiden to chaindata.json. Please consider.

Added RadiumBlock rpc endpoints to chaindata.json

---

data/chaindata.json
dist/chains/all.json
dist/chains/byGenesisHash/0x6bd89e052d67a45bb60a9a23e8581053d5e0d619f15cb9865946937e690c42d6.json
dist/chains/byId/liberland.json

chore: disable liberland

---

data/chaindata.json

- Add DED token on AssetHub
- https://twitter.com/giottodf/status/1770046879868313731?s=52&t=iIITOCrcuNFjDM02cXNoZg
- https://assethub-polkadot.subscan.io/assets/30

chore: add DED on AssetHub

---

assets/chains/neuroweb.svg
assets/chains/rococo-neuro-web-testnet.svg
assets/tokens/neuro.svg

Added NeuroWeb main & test net chain and token logos.

feat: neuroweb main & testnet chain logo, token logo

---

data/chaindata.json

As requested by Aleph Zero team

Add common psp22 contracts on aleph-zero

---

data/testnets-chaindata.json

XSocial disabled, confirmed by Subsocial team via TG

Yeet xsocial testnet

---

data/chaindata.json

Kusama chain no longer maintained according to team TG chat

Yeet hyperbridge kusama

---

data/testnets-chaindata.json

chore: yeet avail goldberg

---

data/chaindata.json

Support for Ike's sA0 token
[Contracts can be found on our github](https://github.com/WaterCoolerStudiosInc/ike-contracts/tree/main/src/share_token
) 
[Contract addresses can be found in our docs](https://docs.ike.xyz/the-ike-protocol/official-contract-addresses)
For any questions, reach out via telegram or [Discord](https://discord.gg/ikeazero)

Add sA0 token

---

data/chaindata.json

XODE assets includes:
- IDON
- MPC
- IMPC
- DON

added new xode tokens
